<?php

/**
 * @file
 * Contains napcs_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function napcs_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the napcs_block module.
    case 'help.page.napcs_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Miscellaneous custom blocks for NAPCS') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function napcs_block_theme($existing, $type, $theme, $path) {
  return [
    'napcs_block_homepage_2col' => [
      'variables' => [
        'columns' => '',
      ],
    ],
  ];
}

/**
 * Implements template_process_HOOK().
 */
function template_preprocess_napcs_block_homepage_2col(&$variables) {
  // Add link render arrays.
  foreach ($variables['columns'] as $delta => $column) {
    if (isset($column['url'])) {
      foreach (['title', 'link_text'] as $element) {
        $attributes = isset($column['link_attributes']) ? $column['link_attributes'] : NULL;
        $variables['columns'][$delta]["{$element}_link"] = [
          '#type' => 'link',
          '#title' => $column[$element],
          '#url' => $column['url'],
          '#attributes' => $attributes,
        ];
      }
    }
  }
}
