<?php

/**
 * @file
 * Contains napcs_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function napcs_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the napcs_migrate module.
    case 'help.page.napcs_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Wordpress -&gt; Drupal migrations for NAPCS') . '</p>';
      return $output;

    default:
  }
}
